sudo: required

language: bash

services:
    - docker

addons:
    apt:
        packages:
            - docker-ce

env:
    # PHP 7.2
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=3.4.*
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=4.2.*
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=4.3.*
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=3.4.*
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=4.2.*
    - PHP_VERSION=7.2 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=4.3.*

    # PHP 7.3
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=3.4.*
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=4.2.*
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=nyholm SYMFONY_VERSION=4.3.*
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=3.4.*
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=4.2.*
    - PHP_VERSION=7.3 PSR_HTTP_PROVIDER=zendframework SYMFONY_VERSION=4.3.*

install:
    - dev/bin/docker-compose build --build-arg PHP_VERSION=${PHP_VERSION} php

before_script:
    # Install symfony/flex to make sure SYMFONY_VERSION is working
    - composer global require symfony/flex --ansi
    - composer config extra.symfony.require "${SYMFONY_VERSION}"
    - composer update --ansi --prefer-dist

script:
    - composer test -- --colors=always --coverage-clover=coverage.xml --debug
    - composer lint -- --ansi --diff --dry-run --using-cache=no --verbose

after_script:
    - dev/bin/docker-compose down --volumes

after_success:
    - bash <(curl -s https://codecov.io/bash)
